---
title: "Reproducible document"
format: html
editor: visual
---

-   Hazal Haytural
-   NNF CBMR
-   University of Copenhagen

# Introduction

this is **introduction**.

# Methods and Results

here we show **method and results**.

## Analysis

here ***analysis*** is shown. *a simple code can be found below.*

```{r}
2+5 
```

# Discussion

here is **discussion**.

```{r setup}
#| message: FALSE
#| warning: FALSE

library(tidyverse)
library(NHANES)

nhanes_small <- read_csv(here::here("data/nhanes_small.csv"))
```

```{r}
nhanes_small

nhanes_small <- nhanes_small %>% select(age, sex, bmi, diabetes, phys_active, bp_sys_ave, bp_dia_ave, education)

nhanes_small
```

# Table of results

```{r}
#| message: FALSE
#| warning: FALSE

nhanes_small %>%
  filter(!is.na(diabetes)) %>%
  group_by(diabetes, education) %>%
  summarise(
    mean_age = mean(age, na.rm = T),
    mean_bmi = mean(bmi, na.rm = T)
  ) %>%
  ungroup() %>%
  knitr::kable(caption = "mean values of age and bmi")
```

# Exercise 8.6 - Prettier table

```{r}
#| echo: FALSE

nhanes_small %>%
  filter(!is.na(diabetes)) %>%
  group_by(diabetes, education) %>%
  summarise(
    mean_age = mean(age, na.rm = T),
    mean_bmi = mean(bmi, na.rm = T)
  ) %>%
  ungroup() %>%
  mutate(
    mean_age = round(mean_age, 1),
    mean_bmi = round(mean_bmi, 1),
    education = str_to_sentence(education)
  ) %>%
  rename(
    "Diabetes Status" = diabetes,
    "Education" = education,
    "Mean Age" = mean_age,
    "Mean BMI" = mean_bmi
  ) %>%
  knitr::kable(caption = "Mean values of age and BMI for each education and diabetes status")
```
